export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Link from "next/link";
import "./global.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className="bg-gray-50 text-gray-900">
        {/* 🔹 상단 고정된 헤더 */}
        <header className="w-full bg-white shadow-md border-b">
          <div className="max-w-3xl mx-auto px-4 py-4 flex justify-center">
            <Link
              href="/"
              className="text-2xl font-semibold text-gray-800 hover:text-blue-600 transition-colors"
            >
              📊 Linkpoll
            </Link>
          </div>
        </header>

        {/* 🔹 실제 페이지 내용 */}
        <main className="max-w-3xl mx-auto px-4 py-8">{children}</main>
      </body>
    </html>
  );
}
